spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CashMate?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: kwonojou1120

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true    # ?? ???? ????? ??
    baseline-version: 1          # ?? ?? ?? (V1 ?? ??)